---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type }}
  namespace: {{ .Values.app.env }}
  labels:
    deploy: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type }}
    app: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type }}
  replicas: {{ (pluck .Values.app.env .Values.image.replicaCount | first).min }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        pods: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type }}
        app: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }} 
    spec:
      {{- if and (has .Values.app.env (list "prd" "uat" )) (index .Values.nodeSelector .Values.app.env) }}
      nodeSelector:
        eks.amazonaws.com/nodegroup: {{ (pluck .Values.app.env .Values.nodeSelector | first) }}
      {{- end }}  
      {{- if and (has .Values.app.env (list "dev" "stg" "prf" )) (index .Values.nodeSelector .Values.app.env) }}
      nodeSelector:
        eks.amazonaws.com/capacityType: {{ (pluck .Values.app.env .Values.nodeSelector | first) }}
      {{- end }}
      # initContainers:
      # - name: init-container
      #   image: alpine
      #   command: ["ls -ld /prometheus"]
      #   volumeMounts:
      #     - name: prom-vol
      #       mountPath: /prometheus
      securityContext:
         runAsUser: 0
      containers:
      - name: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/prometheus"]
        args: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--web.external-url=http://localhost/prometheus"]
        {{- if  index .Values.service "ports" }}
        ports:
        {{- range $key, $val := .Values.service.ports }}
        - containerPort: {{ $val.port }}
          name: {{ $val.name }}
        {{- end }}
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type }}-app
        readinessProbe:
{{ toYaml .Values.health_check | indent 10 }}
        livenessProbe:
{{ toYaml .Values.health_check | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
         - name: prom-vol
           mountPath: /prometheus
         #- name: prometheus-conf-vol
         #  mountPath: /etc/prometheus
      volumes:
        - name: prom-vol
          hostPath:
            path: /prometheus
        #- name: prometheus-conf-vol
        #  configMap:
        #    name: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type  }}-app
        #    items:
        #      - key: prometheus.yml
        #        path: prometheus.yml
