---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.env }}-{{ .Values.global.project }}-{{ .Values.app.component }}-{{ .Values.app.type  }}-sentry
  namespace: {{ .Values.app.env }}
data:
  SENTRY_ORG: {{ "1" | b64enc | quote }}
