# Default values for web chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  component: prometheus
  type: web 
  env: prd

namespace: production

image:
  repository: prom/prometheus 
  pullPolicy: IfNotPresent
  tag: v2.1.0
  replicaCount:
    dev: &non-prod
      min: 1
      max: 1
    stg: *non-prod
    prf:
      min: 1
      max: 100
    uat: *non-prod
    prd:
      min: 10
      max: 50

nodeSelector: 
  prd: "private-cluster-1"
  non_prd: SPOT

resources:
  limits:
    cpu: 1024m
    memory: 1Gi
  requests:
    cpu: 512m
    memory: 500Mi

autoscaling:
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 50

service:
  type: ClusterIP
  internalPort: &port 9090
  externalPort: *port
  name: http

ingress:
  class:
    dev: nginx
    stg: non-prod-nginx
    prf: non-prod-nginx
    uat: prod-nginx
    prd: prod-nginx
  internal:
    status: True
    host: internal-health-pg.devops360.com
    path: /
  external:
    status: True
    host: pg.devops360.com
    paths:
      - /*

health_check:
  httpGet:
    path: /
    port: *port
  initialDelaySeconds: 10 
  periodSeconds: 30
