# Default values for web chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  component: prometheus
  type: web
  env: poc

image:
  repository: prom/prometheus
  pullPolicy: IfNotPresent
  tag: v2.1.0
  replicaCount:
    dev: &non-prod
      min: 1
      max: 1
    stg: *non-prod
    prf:
      min: 1
      max: 100
    uat: *non-prod
    prd:
      min: 10
      max: 50

nodeSelector: 
  prd: "private-cluster-1"
  dev: SPOT
  uat: "private-cluster-1"

resources:
  limits:
    cpu: 2048m
    memory: 4096Mi
  requests:
    cpu: 1024m
    memory: 2048Mi

autoscaling:
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 50

service:
  type: ClusterIP
  ports: 
    - port: &main 9090
      name: http

ingress:
  external:
    host: prom.localdev.me
    rules:
      - port: *main
        paths:
          - /
  internal:
    host: prom-int.localdev.me
    rules:
      - port: *main
        paths:
          - /health

health_check:
  httpGet:
    path: /
    port: *main
  initialDelaySeconds: 10 
  periodSeconds: 30
